export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAIL = "LOGIN_ADMIN_FAIL";

export const LOAD_ADMIN_REQUEST = "LOAD_ADMIN_REQUEST";
export const LOAD_ADMIN_SUCCESS = "LOAD_ADMIN_SUCCESS";
export const LOAD_ADMIN_FAIL = "LOAD_ADMIN_FAIL";

export const UPDATE_PROFILE_ADMIN_REQUEST = "UPDATE_PROFILE_ADMIN_REQUEST";
export const UPDATE_PROFILE_ADMIN_SUCCESS = "UPDATE_PROFILE_ADMIN_SUCCESS";
export const UPDATE_PROFILE_ADMIN_RESET = "UPDATE_PROFILE_ADMIN_RESET";
export const UPDATE_PROFILE_ADMIN_FAIL = "UPDATE_PROFILE_ADMIN_FAIL";

export const UPDATE_PASSWORD_ADMIN_REQUEST = "UPDATE_PASSWORD_ADMIN_REQUEST";
export const UPDATE_PASSWORD_ADMIN_SUCCESS = "UPDATE_PASSWORD_ADMIN_SUCCESS";
export const UPDATE_PASSWORD_ADMIN_RESET = "UPDATE_PASSWORD_ADMIN_RESET";
export const UPDATE_PASSWORD_ADMIN_FAIL = "UPDATE_PASSWORD_ADMIN_FAIL";

//NHANVIEN
export const CREATE_NHANVIEN_REQUEST = "CREATE_NHANVIEN_REQUEST";
export const CREATE_NHANVIEN_SUCCESS = "CREATE_NHANVIEN_SUCCESS";
export const CREATE_NHANVIEN_FAIL = "CREATE_NHANVIEN_FAIL";
export const CREATE_NHANVIEN_RESET = "CREATE_NHANVIEN_RESET";

export const ALL_NHANVIENS_REQUEST = "ALL_NHANVIENS_REQUEST";
export const ALL_NHANVIENS_SUCCESS = "ALL_NHANVIENS_SUCCESS";
export const ALL_NHANVIENS_FAIL = "ALL_NHANVIENS_FAIL";

export const LOGOUT_ADMIN_SUCCESS = "LOGOUT_ADMIN_SUCCESS";
export const LOGOUT_ADMIN_FAIL = "LOGOUT_ADMIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
