export const LOGIN_NHANVIEN_REQUEST = "LOGIN_NHANVIEN_REQUEST";
export const LOGIN_NHANVIEN_SUCCESS = "LOGIN_NHANVIEN_SUCCESS";
export const LOGIN_NHANVIEN_FAIL = "LOGIN_NHANVIEN_FAIL";

export const LOAD_NHANVIEN_REQUEST = "LOAD_NHANVIEN_REQUEST";
export const LOAD_NHANVIEN_SUCCESS = "LOAD_NHANVIEN_SUCCESS";
export const LOAD_NHANVIEN_FAIL = "LOAD_NHANVIEN_FAIL";

export const UPDATE_PROFILE_NHANVIEN_REQUEST =
  "UPDATE_PROFILE_NHANVIEN_REQUEST";
export const UPDATE_PROFILE_NHANVIEN_SUCCESS =
  "UPDATE_PROFILE_NHANVIEN_SUCCESS";
export const UPDATE_PROFILE_NHANVIEN_RESET = "UPDATE_PROFILE_NHANVIEN_RESET";
export const UPDATE_PROFILE_NHANVIEN_FAIL = "UPDATE_PROFILE_NHANVIEN_FAIL";

export const UPDATE_PASSWORD_NHANVIEN_REQUEST =
  "UPDATE_PASSWORD_NHANVIEN_REQUEST";
export const UPDATE_PASSWORD_NHANVIEN_SUCCESS =
  "UPDATE_PASSWORD_NHANVIEN_SUCCESS";
export const UPDATE_PASSWORD_NHANVIEN_RESET = "UPDATE_PASSWORD_NHANVIEN_RESET";
export const UPDATE_PASSWORD_NHANVIEN_FAIL = "UPDATE_PASSWORD_NHANVIEN_FAIL";

export const LOGOUT_NHANVIEN_SUCCESS = "LOGOUT_NHANVIEN_SUCCESS";
export const LOGOUT_NHANVIEN_FAIL = "LOGOUT_NHANVIEN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
