export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST";
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS";
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL";

export const MY_ORDERS_PROCESSING_REQUEST = "MY_ORDERS_PROCESSING_REQUEST";
export const MY_ORDERS_PROCESSING_SUCCESS = "MY_ORDERS_PROCESSING_SUCCESS";
export const MY_ORDERS_PROCESSING_FAIL = "MY_ORDERS_PROCESSING_FAIL";

export const MY_ORDERS_CANCEL_REQUEST = "MY_ORDERS_CANCEL_REQUEST";
export const MY_ORDERS_CANCEL_SUCCESS = "MY_ORDERS_CANCEL_SUCCESS";
export const MY_ORDERS_CANCEL_FAIL = "MY_ORDERS_CANCEL_FAIL";

export const MY_ORDERS_PROCESSED_REQUEST = "MY_ORDERS_PROCESSED_REQUEST";
export const MY_ORDERS_PROCESSED_SUCCESS = "MY_ORDERS_PROCESSED_SUCCESS";
export const MY_ORDERS_PROCESSED_FAIL = "MY_ORDERS_PROCESSED_FAIL";

export const MY_ORDERS_SHIPPING_REQUEST = "MY_ORDERS_SHIPPING_REQUEST";
export const MY_ORDERS_SHIPPING_SUCCESS = "MY_ORDERS_SHIPPING_SUCCESS";
export const MY_ORDERS_SHIPPING_FAIL = "MY_ORDERS_SHIPPING_FAIL";

export const MY_ORDERS_SHIPPED_REQUEST = "MY_ORDERS_SHIPPED_REQUEST";
export const MY_ORDERS_SHIPPED_SUCCESS = "MY_ORDERS_SHIPPED_SUCCESS";
export const MY_ORDERS_SHIPPED_FAIL = "MY_ORDERS_SHIPPED_FAIL";

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_RESET = "CANCEL_ORDER_RESET";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ALL_ORDER_PROCESSING_REQUEST = "ALL_ORDER_PROCESSING_REQUEST";
export const ALL_ORDER_PROCESSING_SUCCESS = "ALL_ORDER_PROCESSING_SUCCESS";
export const ALL_ORDER_PROCESSING_FAIL = "ALL_ORDER_PROCESSING_FAIL";

export const ALL_ORDER_CANCEL_REQUEST = "ALL_ORDER_CANCEL_REQUEST";
export const ALL_ORDER_CANCEL_SUCCESS = "ALL_ORDER_CANCEL_SUCCESS";
export const ALL_ORDER_CANCEL_FAIL = "ALL_ORDER_CANCEL_FAIL";

export const ALL_ORDER_PROCESSED_REQUEST = "ALL_ORDER_PROCESSED_REQUEST";
export const ALL_ORDER_PROCESSED_SUCCESS = "ALL_ORDER_PROCESSED_SUCCESS";
export const ALL_ORDER_PROCESSED_FAIL = "ALL_ORDER_PROCESSED_FAIL";

export const ALL_ORDER_SHIPPING_REQUEST = "ALL_ORDER_SHIPPING_REQUEST";
export const ALL_ORDER_SHIPPING_SUCCESS = "ALL_ORDER_SHIPPING_SUCCESS";
export const ALL_ORDER_SHIPPING_FAIL = "ALL_ORDER_SHIPPING_FAIL";

export const ALL_ORDER_SHIPPED_REQUEST = "ALL_ORDER_SHIPPED_REQUEST";
export const ALL_ORDER_SHIPPED_SUCCESS = "ALL_ORDER_SHIPPED_SUCCESS";
export const ALL_ORDER_SHIPPED_FAIL = "ALL_ORDER_SHIPPED_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
