export const LOGIN_SHIPPER_REQUEST = "LOGIN_SHIPPER_REQUEST";
export const LOGIN_SHIPPER_SUCCESS = "LOGIN_SHIPPER_SUCCESS";
export const LOGIN_SHIPPER_FAIL = "LOGIN_SHIPPER_FAIL";

export const LOAD_SHIPPER_REQUEST = "LOAD_SHIPPER_REQUEST";
export const LOAD_SHIPPER_SUCCESS = "LOAD_SHIPPER_SUCCESS";
export const LOAD_SHIPPER_FAIL = "LOAD_SHIPPER_FAIL";

export const UPDATE_PROFILE_SHIPPER_REQUEST = "UPDATE_PROFILE_SHIPPER_REQUEST";
export const UPDATE_PROFILE_SHIPPER_SUCCESS = "UPDATE_PROFILE_SHIPPER_SUCCESS";
export const UPDATE_PROFILE_SHIPPER_RESET = "UPDATE_PROFILE_SHIPPER_RESET";
export const UPDATE_PROFILE_SHIPPER_FAIL = "UPDATE_PROFILE_SHIPPER_FAIL";

export const UPDATE_PASSWORD_SHIPPER_REQUEST =
  "UPDATE_PASSWORD_SHIPPER_REQUEST";
export const UPDATE_PASSWORD_SHIPPER_SUCCESS =
  "UPDATE_PASSWORD_SHIPPER_SUCCESS";
export const UPDATE_PASSWORD_SHIPPER_RESET = "UPDATE_PASSWORD_SHIPPER_RESET";
export const UPDATE_PASSWORD_SHIPPER_FAIL = "UPDATE_PASSWORD_SHIPPER_FAIL";

export const LOGOUT_SHIPPER_SUCCESS = "LOGOUT_SHIPPER_SUCCESS";
export const LOGOUT_SHIPPER_FAIL = "LOGOUT_SHIPPER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
